[project]
name = "gdpr-api-tester"
authors = [
  { name="Mikko Keskinen", email="mikko.keskinen@hel.fi" },
]
description = "Helsinki Profile GDPR API Tester"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.12"
classifiers = [
    "Intended Audience :: Developers",
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Quality Assurance",
]
dynamic = ["dependencies", "version"]

[project.urls]
"Homepage" = "https://github.com/City-of-Helsinki/profile-gdpr-api-tester"
"Bug Tracker" = "https://github.com/City-of-Helsinki/profile-gdpr-api-tester/issues"

[project.optional-dependencies]
test = [
  "pytest>=8.0",
  "coverage[toml]>=7.6",
  "hatch>=1.14",
  "ruff>=0.13.0",
]
all = [
  "gdpr-api-tester[test]",
]

[project.scripts]
gdpr_api_tester = "gdpr_api_tester.main:main"

[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
version = {file = "VERSION"}

[tool.setuptools.packages]
find = {}

[tool.pytest.ini_options]
pythonpath = "."
testpaths = "tests"
norecursedirs = [
  ".git",
  ".venv",
  "venv",
  "dist",
  "build",
]

[tool.coverage.run]
source = ["gdpr_api_tester"]
relative_files = true
branch = true

[tool.ruff]
target-version = "py312"
line-length = 120

[tool.ruff.lint]
select = [
  # Pyflakes
  "F",
  # pycodestyle
  "E",
  "W",
  # isort
  "I",
  # pep8-naming
  "N",
  # flake8-bugbear without opinionated rules
  "B0",
  # flake8-pie
  "PIE",
  # flake8-print
  "T20",
  # pyupgrade
  "UP",
]
extend-per-file-ignores = { "*/tests/*" = ["E501"], "gdpr_api_tester/main.py" = ["T201"], "gdpr_api_tester/rsa_key.py" = ["T201"] }

[tool.hatch.envs.default]
features = ["test"]

[tool.hatch.envs.default.scripts]
test = "pytest {args}"

[tool.hatch.envs.hatch-test]
default-args = ["tests"]

[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.12", "3.13", "3.14"]

[tool.hatch.envs.hatch-test.scripts]
run = [
  "pytest{env:HATCH_TEST_ARGS:} {args}",
]
run-cov = [
  "coverage run --parallel-mode -m pytest{env:HATCH_TEST_ARGS:} {args}",
]
cov-combine = [
  "coverage combine",
]
cov-report = [
  "coverage report",
]
