[project]
name = "gdpr-api-tester"
authors = [
  { name="Mikko Keskinen", email="mikko.keskinen@hel.fi" },
]
description = "Helsinki Profile GDPR API Tester"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.12"
classifiers = [
    "Intended Audience :: Developers",
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Quality Assurance",
]
dynamic = ["dependencies", "version"]

[project.urls]
"Homepage" = "https://github.com/City-of-Helsinki/profile-gdpr-api-tester"
"Bug Tracker" = "https://github.com/City-of-Helsinki/profile-gdpr-api-tester/issues"

[project.optional-dependencies]
test = [
  "pytest>=8.0",
  "coverage[toml]>=7.6",
  "hatch>=1.14",
]
all = [
  "gdpr-api-tester[test]",
]

[project.scripts]
gdpr_api_tester = "gdpr_api_tester.main:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
version = {file = "VERSION"}

[tool.setuptools.packages]
find = {}

[tool.pytest.ini_options]
pythonpath = "."
testpaths = "tests"
norecursedirs = [
  ".git",
  ".venv",
  "venv",
  "dist",
  "build",
]

[tool.coverage.run]
source = ["gdpr_api_tester"]
relative_files = true
branch = true

[tool.hatch.envs.default]
features = ["test"]

[tool.hatch.envs.default.scripts]
test = "pytest {args}"

[tool.hatch.envs.hatch-test]
default-args = ["tests"]

[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.12", "3.13", "3.14"]

[tool.hatch.envs.hatch-test.scripts]
run = [
  "pytest{env:HATCH_TEST_ARGS:} {args}",
]
run-cov = [
  "coverage run --parallel-mode -m pytest{env:HATCH_TEST_ARGS:} {args}",
]
cov-combine = [
  "coverage combine",
]
cov-report = [
  "coverage report",
]
