sonar.projectKey=City-of-Helsinki_profile-gdpr-api-tester
sonar.organization=city-of-helsinki
sonar.python.version=3.12
sonar.python.coverage.reportPaths=.coverage-reports/coverage-*.xml
sonar.test.inclusions=**/tests/**/*
sonar.exclusions=**/migrations/*,docs/**/*
